gcp_credentials: ENCRYPTED[9cf993f6cc2ab666aa2d428185257608d065f6468146aaa26d6d2f31e88ed8045d7dd615cd5c7c83d7bcf12578762869]

task:
  name: build
  timeout_in: 60m
  gke_container:
    image: gradle:4.9.0-jdk8
    cluster_name: cirrus-ci-cluster
    zone: us-central1-a
    namespace: default
    cpu: 3
    memory: 4G
  gradle_cache:
    folder: ~/.gradle/caches
  env:
    GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx1G -XX:MaxRAMFraction=1 -XX:+HeapDumpOnOutOfMemoryError"
  script:
    - printenv
    - java -version
    - gradle build --no-daemon --build-cache -Ptime-tracker --parallel
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -f ~/.gradle/caches/build-cache-1/cache.properties
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
